paths = [
    "~/.config/alacritty",
    "~/.config/hypr",
    "~/.config/nvim",
    "~/.p10k.zsh",
    "~/.config/lazydot.toml",
    "~/.icons",
    "~/.tmux.conf",
    "~/.config/firewalld",
    "~/.local/share/winbox",
    "~/.local/open-webui",
    "~/.config/docker-firewall",
    "~/.config/waybar",
]
